-- The database as the old service's Hibernate left it (read from the live weather-db on 18 September
-- 2026): the four tables Gully keeps, with the Hub's key in one of them, and one of the four it does
-- not read any more. Gully's V1 migration must run over this and leave the key working.
create table api_key (
    id bigint generated by default as identity primary key,
    consumer varchar(64) not null,
    created_at timestamp(6) with time zone not null,
    created_by varchar(64) not null,
    key_hash varchar(64) not null,
    key_prefix varchar(16) not null,
    last_used_at timestamp(6) with time zone,
    revoked_at timestamp(6) with time zone,
    scope varchar(256) not null,
    constraint ukc3kxypboi2preufocp17cterb unique (key_hash)
);
create table console_user (
    id bigint generated by default as identity primary key,
    code_hash varchar(128) not null,
    created_at timestamp(6) with time zone not null,
    failed_attempts integer not null,
    last_login_at timestamp(6) with time zone,
    locked_until timestamp(6) with time zone,
    username varchar(64) not null,
    constraint ukpfww6yekj2elvdkft25i75vya unique (username)
);
create table log_event (
    id bigint generated by default as identity primary key,
    count bigint not null,
    exception varchar(256),
    first_seen_at timestamp(6) with time zone not null,
    last_seen_at timestamp(6) with time zone not null,
    level varchar(8) not null,
    logger varchar(192) not null,
    message varchar(2048) not null,
    pattern varchar(512) not null,
    signature varchar(40) not null,
    source_id varchar(64),
    thread varchar(64),
    trace text
);
create unique index ix_log_event_signature on log_event (signature);
create index ix_log_event_level_seen on log_event (level, last_seen_at);
create table api_access_log (
    id bigint generated by default as identity primary key,
    api_key_id bigint,
    at timestamp(6) with time zone not null,
    consumer varchar(64),
    method varchar(8) not null,
    path varchar(512) not null,
    query varchar(1024),
    remote_ip varchar(64),
    status integer not null
);
create index ix_api_access_key_at on api_access_log (api_key_id, at);
create table weather_call (
    id bigint generated by default as identity primary key,
    provider varchar(32) not null,
    at timestamp(6) with time zone not null,
    weight double precision not null,
    ok boolean not null,
    latency_ms bigint,
    detail varchar(512)
);
insert into api_key (consumer, created_at, created_by, key_hash, key_prefix, scope)
values ('hub', now(), 'operator', 'c772f0e29b8bfbccb736c7a84bc5b368f2db19490e0ec2b984117edd3010e68b', 'weather_end-', 'ALL');
