-- Gully's schema, owned by Flyway. Every table the service reads or writes is here; there is no entity
-- manager and nothing else creates a table. Started over on 21 September 2026 (W-1): the platform, the
-- upstream ledger, the console's settings, and the Bureau's stations. What a station holds beyond its
-- place - its latest values - lives in memory and is ten minutes old at most.

-- ---------------------------------------------------------------- the platform

create table if not exists api_key (
    id            bigint generated by default as identity primary key,
    consumer      varchar(64)  not null,
    created_at    timestamptz  not null,
    created_by    varchar(64)  not null,
    key_hash      varchar(64)  not null unique,
    key_prefix    varchar(16)  not null,
    last_used_at  timestamptz,
    revoked_at    timestamptz,
    scope         varchar(256) not null default 'ALL'
);

create table if not exists console_user (
    id              bigint generated by default as identity primary key,
    code_hash       varchar(128) not null,
    created_at      timestamptz  not null,
    failed_attempts integer      not null default 0,
    last_login_at   timestamptz,
    locked_until    timestamptz,
    username        varchar(64)  not null unique
);

create table if not exists api_access_log (
    id         bigint generated by default as identity primary key,
    api_key_id bigint,
    at         timestamptz   not null,
    consumer   varchar(64),
    method     varchar(8)    not null,
    path       varchar(512)  not null,
    query      varchar(1024),
    remote_ip  varchar(64),
    status     integer       not null
);
create index if not exists ix_api_access_key_at on api_access_log (api_key_id, at);

create table if not exists log_event (
    id            bigint generated by default as identity primary key,
    count         bigint        not null,
    exception     varchar(256),
    first_seen_at timestamptz   not null,
    last_seen_at  timestamptz   not null,
    level         varchar(8)    not null,
    logger        varchar(192)  not null,
    message       varchar(2048) not null,
    pattern       varchar(512)  not null,
    signature     varchar(40)   not null unique,
    source_id     varchar(64),
    thread        varchar(64),
    trace         text
);
create index if not exists ix_log_event_level_seen on log_event (level, last_seen_at);

-- What the console sets and a restart must keep: one row per value, the value as text and the reader
-- knowing its shape.
create table if not exists setting (
    key        varchar(64)  primary key,
    value      text         not null,
    updated_by varchar(64),
    updated_at timestamptz  not null
);

-- ---------------------------------------------------------------- the upstreams

-- Every upstream call, written before it is counted: the budget counts from here.
create table if not exists upstream_call (
    id         bigint generated always as identity primary key,
    upstream   varchar(32) not null,
    at         timestamptz not null,
    units      double precision not null,
    ok         boolean     not null,
    latency_ms bigint,
    detail     varchar(512)
);
create index if not exists ix_upstream_call_upstream_at on upstream_call (upstream, at);

-- ---------------------------------------------------------------- the Bureau

-- Every station the state file has ever named, as the file describes it.
create table if not exists station (
    id            varchar(16)  primary key,
    wmo_id        varchar(16),
    name          varchar(128) not null,
    lat           double precision not null,
    lon           double precision not null,
    height_m      double precision,
    zone          varchar(48),
    district      varchar(16),
    state         varchar(8)   not null,
    first_seen_at timestamptz  not null,
    last_seen_at  timestamptz  not null
);
